const fs = require('fs');
const path = '.kiro/specs/aws-deployment-infrastructure/design.md';

const s = [];

s.push(`## Components and Interfaces`);
s.push(``);
s.push(`### 1. Backend Containerization and ECR Setup`);
s.push(``);
s.push(`#### Dockerfile`);
s.push(``);
s.push(`The backend Dockerfile uses a multi-stage build to minimize image size and exclude development dependencies:`);
s.push(``);
s.push('```dockerfile');
s.push(`# Stage 1: Build`);
s.push(`FROM node:20-alpine AS builder`);
s.push(`WORKDIR /app`);
s.push(``);
s.push(`# Copy package files first for layer caching`);
s.push(`COPY package*.json ./`);
s.push(`RUN npm ci --include=dev`);
s.push(``);
s.push(`# Copy source and compile TypeScript`);
s.push(`COPY tsconfig.json ./`);
s.push(`COPY src/ ./src/`);
s.push(`RUN npm run build`);
s.push(``);
s.push(`# Stage 2: Production`);
s.push(`FROM node:20-alpine AS production`);
s.push(`WORKDIR /app`);
s.push(``);
s.push(`# Security: run as non-root user`);
s.push(`RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001`);
s.push(``);
s.push(`# Copy only production dependencies`);
s.push(`COPY package*.json ./`);
s.push(`RUN npm ci --omit=dev && npm cache clean --force`);
s.push(``);
s.push(`# Copy compiled output from builder`);
s.push(`COPY --from=builder /app/dist ./dist`);
s.push(``);
s.push(`# Copy static data files needed at runtime`);
s.push(`COPY --from=builder /app/src/data ./src/data`);
s.push(``);
s.push(`USER nodejs`);
s.push(`EXPOSE 3000`);
s.push(``);
s.push(`# Health check built into image`);
s.push(`HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \\`);
s.push(`  CMD wget -qO- http://localhost:3000/api/health || exit 1`);
s.push(``);
s.push(`CMD ["node", "dist/index.js"]`);
s.push('```');
s.push(``);
s.push(`#### ECR Repository Configuration`);
s.push(``);
s.push(`ECR repository settings (defined in CDK):`);
s.push(``);
s.push('```typescript');
s.push(`// infrastructure/lib/ecr-stack.ts`);
s.push(`import * as ecr from 'aws-cdk-lib/aws-ecr';`);
s.push(`import * as cdk from 'aws-cdk-lib';`);
s.push(``);
s.push(`const repository = new ecr.Repository(this, 'BackendRepo', {`);
s.push(`  repositoryName: 'afct-prod-ecr-backend',`);
s.push(`  imageScanOnPush: true,           // Req 1.4: automatic vulnerability scanning`);
s.push(`  imageTagMutability: ecr.TagMutability.MUTABLE,`);
s.push(`  lifecycleRules: [`);
s.push(`    {`);
s.push(`      // Keep last 10 tagged images`);
s.push(`      maxImageCount: 10,`);
s.push(`      tagStatus: ecr.TagStatus.TAGGED,`);
s.push(`      tagPrefixList: ['v'],`);
s.push(`    },`);
s.push(`    {`);
s.push(`      // Remove untagged images after 1 day`);
s.push(`      maxImageAge: cdk.Duration.days(1),`);
s.push(`      tagStatus: ecr.TagStatus.UNTAGGED,`);
s.push(`    },`);
s.push(`  ],`);
s.push(`  encryptionKey: kmsKey,           // KMS encryption for images at rest`);
s.push(`  removalPolicy: cdk.RemovalPolicy.RETAIN,`);
s.push(`});`);
s.push('```');
s.push(``);
s.push(`#### Image Tagging Strategy`);
s.push(``);
s.push(`Images are tagged with both a semantic version and \`latest\`:`);
s.push(``);
s.push('```bash');
s.push(`# Build and tag`);
s.push(`VERSION=$(git describe --tags --abbrev=0 || echo "v1.0.0")`);
s.push(`COMMIT=$(git rev-parse --short HEAD)`);
s.push(`IMAGE_TAG="${VERSION}-${COMMIT}"`);
s.push(``);
s.push(`docker build -t afct-prod-ecr-backend:${IMAGE_TAG} .`);
s.push(`docker tag afct-prod-ecr-backend:${IMAGE_TAG} afct-prod-ecr-backend:latest`);
s.push(``);
s.push(`# Push to ECR`);
s.push(`aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account-id>.dkr.ecr.us-east-1.amazonaws.com`);
s.push(`docker push <account-id>.dkr.ecr.us-east-1.amazonaws.com/afct-prod-ecr-backend:${IMAGE_TAG}`);
s.push(`docker push <account-id>.dkr.ecr.us-east-1.amazonaws.com/afct-prod-ecr-backend:latest`);
s.push('```');
s.push(``);
s.push(`#### Vulnerability Scanning Pipeline Gate`);
s.push(``);
s.push(`After pushing, the CI/CD pipeline checks scan results before deploying (Req 1.5):`);
s.push(``);
s.push('```bash');
s.push(`#!/bin/bash`);
s.push(`# scripts/check-ecr-scan.sh`);
s.push(`IMAGE_TAG=$1`);
s.push(`REPO="afct-prod-ecr-backend"`);
s.push(``);
s.push(`# Wait for scan to complete (up to 5 minutes)`);
s.push(`for i in $(seq 1 30); do`);
s.push(`  STATUS=$(aws ecr describe-image-scan-findings \\`);
s.push(`    --repository-name $REPO \\`);
s.push(`    --image-id imageTag=$IMAGE_TAG \\`);
s.push(`    --query 'imageScanStatus.status' --output text)`);
s.push(`  [ "$STATUS" = "COMPLETE" ] && break`);
s.push(`  sleep 10`);
s.push(`done`);
s.push(``);
s.push(`# Check for CRITICAL or HIGH findings`);
s.push(`CRITICAL=$(aws ecr describe-image-scan-findings \\`);
s.push(`  --repository-name $REPO \\`);
s.push(`  --image-id imageTag=$IMAGE_TAG \\`);
s.push(`  --query 'imageScanFindings.findingSeverityCounts.CRITICAL' --output text)`);
s.push(``);
s.push(`HIGH=$(aws ecr describe-image-scan-findings \\`);
s.push(`  --repository-name $REPO \\`);
s.push(`  --image-id imageTag=$IMAGE_TAG \\`);
s.push(`  --query 'imageScanFindings.findingSeverityCounts.HIGH' --output text)`);
s.push(``);
s.push(`if [ "$CRITICAL" != "None" ] && [ "$CRITICAL" -gt 0 ]; then`);
s.push(`  echo "CRITICAL vulnerabilities found: $CRITICAL. Halting deployment."`);
s.push(`  aws sns publish --topic-arn $SECURITY_SNS_TOPIC --message "ECR scan found $CRITICAL CRITICAL vulnerabilities in $REPO:$IMAGE_TAG"`);
s.push(`  exit 1`);
s.push(`fi`);
s.push(``);
s.push(`if [ "$HIGH" != "None" ] && [ "$HIGH" -gt 0 ]; then`);
s.push(`  echo "HIGH vulnerabilities found: $HIGH. Halting deployment."`);
s.push(`  aws sns publish --topic-arn $SECURITY_SNS_TOPIC --message "ECR scan found $HIGH HIGH vulnerabilities in $REPO:$IMAGE_TAG"`);
s.push(`  exit 1`);
s.push(`fi`);
s.push(``);
s.push(`echo "No CRITICAL or HIGH vulnerabilities found. Proceeding with deployment."`);
s.push('```');
s.push(``);

const existing = fs.readFileSync(path, 'utf8');
fs.writeFileSync(path, existing + s.join('\n'), 'utf8');
console.log('Appended ECR section,', s.length, 'lines');
